"""rh: mes como periodo contabilistico e associado ao exercicio

Revision ID: 3b2555b19810
Revises: 66adea5b995b
Create Date: 2026-08-07 18:13:33.499342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2555b19810'
down_revision: Union[str, Sequence[str], None] = '66adea5b995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rh_alteracoes', sa.Column('exercicio_id', sa.Uuid(), nullable=True))
    op.alter_column('rh_alteracoes', 'mes',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_constraint(op.f('alteracao_mes'), 'rh_alteracoes', type_='unique')
    op.create_unique_constraint('alteracao_mes', 'rh_alteracoes', ['empresa_id', 'colaborador_id', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_rh_alteracoes_exercicio_id'), 'rh_alteracoes', ['exercicio_id'], unique=False)
    op.create_foreign_key(op.f('fk_rh_alteracoes_exercicio_id_exercicios'), 'rh_alteracoes', 'exercicios', ['exercicio_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rh_honorarios', 'mes',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.add_column('rh_mapa_irt', sa.Column('exercicio_id', sa.Uuid(), nullable=True))
    op.alter_column('rh_mapa_irt', 'mes',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_constraint(op.f('mapa_irt_mes'), 'rh_mapa_irt', type_='unique')
    op.create_unique_constraint('mapa_irt_mes', 'rh_mapa_irt', ['empresa_id', 'colaborador_id', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_rh_mapa_irt_exercicio_id'), 'rh_mapa_irt', ['exercicio_id'], unique=False)
    op.create_foreign_key(op.f('fk_rh_mapa_irt_exercicio_id_exercicios'), 'rh_mapa_irt', 'exercicios', ['exercicio_id'], ['id'], ondelete='CASCADE')
    op.add_column('rh_pagamentos', sa.Column('exercicio_id', sa.Uuid(), nullable=True))
    op.alter_column('rh_pagamentos', 'mes',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_constraint(op.f('pagamento_mes'), 'rh_pagamentos', type_='unique')
    op.create_unique_constraint('pagamento_mes', 'rh_pagamentos', ['empresa_id', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_rh_pagamentos_exercicio_id'), 'rh_pagamentos', ['exercicio_id'], unique=False)
    op.create_foreign_key(op.f('fk_rh_pagamentos_exercicio_id_exercicios'), 'rh_pagamentos', 'exercicios', ['exercicio_id'], ['id'], ondelete='CASCADE')
    op.add_column('rh_processamentos', sa.Column('exercicio_id', sa.Uuid(), nullable=True))
    op.alter_column('rh_processamentos', 'mes',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_constraint(op.f('processamento_mes'), 'rh_processamentos', type_='unique')
    op.create_unique_constraint('processamento_mes', 'rh_processamentos', ['empresa_id', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_rh_processamentos_exercicio_id'), 'rh_processamentos', ['exercicio_id'], unique=False)
    op.create_foreign_key(op.f('fk_rh_processamentos_exercicio_id_exercicios'), 'rh_processamentos', 'exercicios', ['exercicio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rh_processamentos_exercicio_id_exercicios'), 'rh_processamentos', type_='foreignkey')
    op.drop_index(op.f('ix_rh_processamentos_exercicio_id'), table_name='rh_processamentos')
    op.drop_constraint('processamento_mes', 'rh_processamentos', type_='unique')
    op.create_unique_constraint(op.f('processamento_mes'), 'rh_processamentos', ['empresa_id', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('rh_processamentos', 'mes',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('rh_processamentos', 'exercicio_id')
    op.drop_constraint(op.f('fk_rh_pagamentos_exercicio_id_exercicios'), 'rh_pagamentos', type_='foreignkey')
    op.drop_index(op.f('ix_rh_pagamentos_exercicio_id'), table_name='rh_pagamentos')
    op.drop_constraint('pagamento_mes', 'rh_pagamentos', type_='unique')
    op.create_unique_constraint(op.f('pagamento_mes'), 'rh_pagamentos', ['empresa_id', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('rh_pagamentos', 'mes',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('rh_pagamentos', 'exercicio_id')
    op.drop_constraint(op.f('fk_rh_mapa_irt_exercicio_id_exercicios'), 'rh_mapa_irt', type_='foreignkey')
    op.drop_index(op.f('ix_rh_mapa_irt_exercicio_id'), table_name='rh_mapa_irt')
    op.drop_constraint('mapa_irt_mes', 'rh_mapa_irt', type_='unique')
    op.create_unique_constraint(op.f('mapa_irt_mes'), 'rh_mapa_irt', ['empresa_id', 'colaborador_id', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('rh_mapa_irt', 'mes',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('rh_mapa_irt', 'exercicio_id')
    op.alter_column('rh_honorarios', 'mes',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_rh_alteracoes_exercicio_id_exercicios'), 'rh_alteracoes', type_='foreignkey')
    op.drop_index(op.f('ix_rh_alteracoes_exercicio_id'), table_name='rh_alteracoes')
    op.drop_constraint('alteracao_mes', 'rh_alteracoes', type_='unique')
    op.create_unique_constraint(op.f('alteracao_mes'), 'rh_alteracoes', ['empresa_id', 'colaborador_id', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('rh_alteracoes', 'mes',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_column('rh_alteracoes', 'exercicio_id')
    # ### end Alembic commands ###
