"""segundo factor totp no utilizador

Revision ID: 40a9bbcc03e5
Revises: 88e8b7269291
Create Date: 2026-08-08 16:23:07.953600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a9bbcc03e5'
down_revision: Union[str, Sequence[str], None] = '88e8b7269291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_segredo', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('totp_ativo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('totp_ativado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_ultimo_contador', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('totp_codigos_recuperacao', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('users', sa.Column('totp_falhas', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('totp_bloqueado_ate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_bloqueado_ate')
    op.drop_column('users', 'totp_falhas')
    op.drop_column('users', 'totp_codigos_recuperacao')
    op.drop_column('users', 'totp_ultimo_contador')
    op.drop_column('users', 'totp_ativado_em')
    op.drop_column('users', 'totp_ativo')
    op.drop_column('users', 'totp_segredo')
    # ### end Alembic commands ###
