"""consultas de IA

Revision ID: 560ebaa204e9
Revises: 3b2555b19810
Create Date: 2026-08-07 18:50:50.680597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560ebaa204e9'
down_revision: Union[str, Sequence[str], None] = '3b2555b19810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ia_consultas',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dados_enviados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entidades_pseudonimizadas', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_saida', sa.Integer(), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_ia_consultas_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ia_consultas_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ia_consultas'))
    )
    op.create_index(op.f('ix_ia_consultas_empresa_id'), 'ia_consultas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ia_consultas_user_id'), 'ia_consultas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ia_consultas_user_id'), table_name='ia_consultas')
    op.drop_index(op.f('ix_ia_consultas_empresa_id'), table_name='ia_consultas')
    op.drop_table('ia_consultas')
    # ### end Alembic commands ###
