"""campo apuramento no exercicio

Revision ID: 66adea5b995b
Revises: 750f78a10dae
Create Date: 2026-08-07 17:33:18.651215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66adea5b995b'
down_revision: Union[str, Sequence[str], None] = '750f78a10dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercicios', sa.Column('apuramento', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercicios', 'apuramento')
    # ### end Alembic commands ###
