"""esquema inicial: empresas, licencas, utilizadores e exercicios

Revision ID: 6e44a606cd6d
Revises: 
Create Date: 2026-08-07 16:27:27.546878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e44a606cd6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('regime_historico', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forma_juridica', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas'))
    )
    op.create_index(op.f('ix_empresas_estado'), 'empresas', ['estado'], unique=False)
    op.create_index(op.f('ix_empresas_nif'), 'empresas', ['nif'], unique=True)
    op.create_table('config_empresa',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('modulos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parametrizacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_config_empresa_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_empresa'))
    )
    op.create_index(op.f('ix_config_empresa_empresa_id'), 'config_empresa', ['empresa_id'], unique=True)
    op.create_table('exercicios',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_exercicios_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercicios')),
    sa.UniqueConstraint('empresa_id', 'nome', name='exercicio_nome')
    )
    op.create_index(op.f('ix_exercicios_empresa_id'), 'exercicios', ['empresa_id'], unique=False)
    op.create_table('users',
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('aprovado_por_id', sa.Uuid(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modulos_permitidos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissoes_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permissoes_accao', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['users.id'], name=op.f('fk_users_aprovado_por_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_users_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_empresa_id'), 'users', ['empresa_id'], unique=False)
    op.create_table('licencas',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('titular', sa.String(length=200), nullable=False),
    sa.Column('plano', sa.String(length=60), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('modulos_incluidos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limite_utilizadores', sa.Integer(), nullable=True),
    sa.Column('aprovada_por_id', sa.Uuid(), nullable=True),
    sa.Column('aprovada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovada_por_id'], ['users.id'], name=op.f('fk_licencas_aprovada_por_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_licencas_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas'))
    )
    op.create_index(op.f('ix_licencas_chave'), 'licencas', ['chave'], unique=True)
    op.create_index(op.f('ix_licencas_empresa_id'), 'licencas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_licencas_estado'), 'licencas', ['estado'], unique=False)
    op.create_table('pedidos_licenca',
    sa.Column('nome_empresa', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('email_contacto', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('responsavel', sa.String(length=200), nullable=False),
    sa.Column('plano_pretendido', sa.String(length=60), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('decidido_por_id', sa.Uuid(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_recusa', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decidido_por_id'], ['users.id'], name=op.f('fk_pedidos_licenca_decidido_por_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_pedidos_licenca_empresa_id_empresas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos_licenca')),
    sa.UniqueConstraint('nif', 'estado', name='pedido_nif_estado')
    )
    op.create_index(op.f('ix_pedidos_licenca_estado'), 'pedidos_licenca', ['estado'], unique=False)
    op.create_index(op.f('ix_pedidos_licenca_nif'), 'pedidos_licenca', ['nif'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_licenca_nif'), table_name='pedidos_licenca')
    op.drop_index(op.f('ix_pedidos_licenca_estado'), table_name='pedidos_licenca')
    op.drop_table('pedidos_licenca')
    op.drop_index(op.f('ix_licencas_estado'), table_name='licencas')
    op.drop_index(op.f('ix_licencas_empresa_id'), table_name='licencas')
    op.drop_index(op.f('ix_licencas_chave'), table_name='licencas')
    op.drop_table('licencas')
    op.drop_index(op.f('ix_users_empresa_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercicios_empresa_id'), table_name='exercicios')
    op.drop_table('exercicios')
    op.drop_index(op.f('ix_config_empresa_empresa_id'), table_name='config_empresa')
    op.drop_table('config_empresa')
    op.drop_index(op.f('ix_empresas_nif'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_estado'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
