"""nulls not distinct nas sequencias, fechos de diario e notas

Revision ID: 750f78a10dae
Revises: d367d890fe71
Create Date: 2026-08-07 16:54:34.949799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750f78a10dae'
down_revision: Union[str, Sequence[str], None] = 'd367d890fe71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diario_fecho'), 'diario_fechos', type_='unique')
    op.create_unique_constraint('diario_fecho', 'diario_fechos', ['empresa_id', 'diario_codigo', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('nota_texto'), 'notas_texto', type_='unique')
    op.create_unique_constraint('nota_texto', 'notas_texto', ['empresa_id', 'numero', 'exercicio_id'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('sequencia_documento'), 'sequencias_documento', type_='unique')
    op.create_unique_constraint('sequencia_documento', 'sequencias_documento', ['empresa_id', 'documento_codigo', 'exercicio_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sequencia_documento', 'sequencias_documento', type_='unique')
    op.create_unique_constraint(op.f('sequencia_documento'), 'sequencias_documento', ['empresa_id', 'documento_codigo', 'exercicio_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('nota_texto', 'notas_texto', type_='unique')
    op.create_unique_constraint(op.f('nota_texto'), 'notas_texto', ['empresa_id', 'numero', 'exercicio_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('diario_fecho', 'diario_fechos', type_='unique')
    op.create_unique_constraint(op.f('diario_fecho'), 'diario_fechos', ['empresa_id', 'diario_codigo', 'exercicio_id', 'mes'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
