"""registo de auditoria

Revision ID: 87a40e0f5839
Revises: a94382fb9fd2
Create Date: 2026-08-08 13:40:15.165265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87a40e0f5839'
down_revision: Union[str, Sequence[str], None] = 'a94382fb9fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=200), nullable=True),
    sa.Column('actor_nome', sa.String(length=200), nullable=True),
    sa.Column('actor_perfil', sa.String(length=20), nullable=True),
    sa.Column('accao', sa.String(length=60), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=True),
    sa.Column('alvo_id', sa.Uuid(), nullable=True),
    sa.Column('alvo_desc', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_auditoria_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_auditoria_empresa_id_empresas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria'))
    )
    op.create_index(op.f('ix_auditoria_accao'), 'auditoria', ['accao'], unique=False)
    op.create_index(op.f('ix_auditoria_actor_id'), 'auditoria', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auditoria_alvo_id'), 'auditoria', ['alvo_id'], unique=False)
    op.create_index(op.f('ix_auditoria_criado_em'), 'auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_auditoria_empresa_id'), 'auditoria', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_empresa_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_criado_em'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_alvo_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_actor_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accao'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
