"""custo estimado por consulta de ia

Revision ID: 88e8b7269291
Revises: 87a40e0f5839
Create Date: 2026-08-08 14:03:54.405339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e8b7269291'
down_revision: Union[str, Sequence[str], None] = '87a40e0f5839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ia_consultas', sa.Column('custo', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ia_consultas', 'custo')
    # ### end Alembic commands ###
