"""exercicio nos honorarios

Revision ID: 9f38a0570ea5
Revises: a581f158c3d6
Create Date: 2026-08-07 22:37:51.282217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38a0570ea5'
down_revision: Union[str, Sequence[str], None] = 'a581f158c3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rh_honorarios', sa.Column('exercicio_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_rh_honorarios_exercicio_id'), 'rh_honorarios', ['exercicio_id'], unique=False)
    op.create_foreign_key(op.f('fk_rh_honorarios_exercicio_id_exercicios'), 'rh_honorarios', 'exercicios', ['exercicio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rh_honorarios_exercicio_id_exercicios'), 'rh_honorarios', type_='foreignkey')
    op.drop_index(op.f('ix_rh_honorarios_exercicio_id'), table_name='rh_honorarios')
    op.drop_column('rh_honorarios', 'exercicio_id')
    # ### end Alembic commands ###
