"""campos do artigo em falta face ao piloto

Revision ID: a581f158c3d6
Revises: 560ebaa204e9
Create Date: 2026-08-07 21:15:54.244625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a581f158c3d6'
down_revision: Union[str, Sequence[str], None] = '560ebaa204e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('subfamilia', sa.String(length=120), nullable=True))
    op.add_column('artigos', sa.Column('cod_barras', sa.String(length=60), nullable=True))
    op.add_column('artigos', sa.Column('conta_proveito', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'conta_proveito')
    op.drop_column('artigos', 'cod_barras')
    op.drop_column('artigos', 'subfamilia')
    # ### end Alembic commands ###
