"""tabelas de dominio: contabilidade, terceiros, comercial, logistica, rh, imobilizados

Revision ID: d367d890fe71
Revises: 6e44a606cd6d
Create Date: 2026-08-07 16:39:46.813325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd367d890fe71'
down_revision: Union[str, Sequence[str], None] = '6e44a606cd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armazens',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_armazens_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_armazens')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='armazem_codigo')
    )
    op.create_index(op.f('ix_armazens_empresa_id'), 'armazens', ['empresa_id'], unique=False)
    op.create_table('artigos',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('familia', sa.String(length=120), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('tipo_artigo', sa.String(length=40), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('preco_compra', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxa_iva', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stock_min', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('conta_existencia', sa.String(length=20), nullable=True),
    sa.Column('conta_custo', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_artigos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artigos')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='artigo_codigo')
    )
    op.create_index(op.f('ix_artigos_descricao'), 'artigos', ['descricao'], unique=False)
    op.create_index(op.f('ix_artigos_empresa_id'), 'artigos', ['empresa_id'], unique=False)
    op.create_table('ativos',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('designacao', sa.String(length=300), nullable=False),
    sa.Column('conta_imob', sa.String(length=20), nullable=True),
    sa.Column('conta_amort_acum', sa.String(length=20), nullable=True),
    sa.Column('conta_custo_amort', sa.String(length=20), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('amort_acumulada', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_ativos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ativos')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='ativo_codigo')
    )
    op.create_index(op.f('ix_ativos_empresa_id'), 'ativos', ['empresa_id'], unique=False)
    op.create_table('centros_custo',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('responsavel', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_centros_custo_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centros_custo')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='centro_codigo')
    )
    op.create_index(op.f('ix_centros_custo_empresa_id'), 'centros_custo', ['empresa_id'], unique=False)
    op.create_table('colaboradores',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('salario_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subsidios', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subsidio_ferias', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subsidio_natal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subs_nao_sujeitos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('iban', sa.String(length=60), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('num_ss', sa.String(length=30), nullable=True),
    sa.Column('provincia', sa.String(length=40), nullable=True),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_colaboradores_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colaboradores')),
    sa.UniqueConstraint('empresa_id', 'numero', name='colaborador_numero')
    )
    op.create_index(op.f('ix_colaboradores_empresa_id'), 'colaboradores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_colaboradores_nome'), 'colaboradores', ['nome'], unique=False)
    op.create_table('contas',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('natureza', sa.String(length=1), nullable=False),
    sa.Column('classe_iva', sa.String(length=20), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_contas_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='conta_codigo')
    )
    op.create_index('ix_contas_empresa_codigo', 'contas', ['empresa_id', 'codigo'], unique=False)
    op.create_index(op.f('ix_contas_empresa_id'), 'contas', ['empresa_id'], unique=False)
    op.create_table('diarios',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_diarios_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diarios')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='diario_codigo')
    )
    op.create_index(op.f('ix_diarios_empresa_id'), 'diarios', ['empresa_id'], unique=False)
    op.create_table('documentos_contabilisticos',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('diario_codigo', sa.String(length=10), nullable=False),
    sa.Column('conta_debito', sa.String(length=20), nullable=True),
    sa.Column('conta_credito', sa.String(length=20), nullable=True),
    sa.Column('retencao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_documentos_contabilisticos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos_contabilisticos')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='documento_codigo')
    )
    op.create_index(op.f('ix_documentos_contabilisticos_empresa_id'), 'documentos_contabilisticos', ['empresa_id'], unique=False)
    op.create_table('fluxos',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_fluxos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fluxos')),
    sa.UniqueConstraint('empresa_id', 'codigo', name='fluxo_codigo')
    )
    op.create_index(op.f('ix_fluxos_empresa_id'), 'fluxos', ['empresa_id'], unique=False)
    op.create_table('rh_independentes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('atividade', sa.String(length=200), nullable=True),
    sa.Column('taxa_ret', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_independentes_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_independentes'))
    )
    op.create_index(op.f('ix_rh_independentes_empresa_id'), 'rh_independentes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rh_independentes_nome'), 'rh_independentes', ['nome'], unique=False)
    op.create_table('sequencias_venda',
    sa.Column('prefixo', sa.String(length=6), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_sequencias_venda_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequencias_venda')),
    sa.UniqueConstraint('empresa_id', 'prefixo', 'ano', name='sequencia_venda')
    )
    op.create_index(op.f('ix_sequencias_venda_empresa_id'), 'sequencias_venda', ['empresa_id'], unique=False)
    op.create_table('terceiros',
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('morada2', sa.String(length=300), nullable=True),
    sa.Column('localidade', sa.String(length=120), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('provincia', sa.String(length=40), nullable=True),
    sa.Column('pais', sa.String(length=60), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('telefone2', sa.String(length=40), nullable=True),
    sa.Column('fax', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('web', sa.String(length=200), nullable=True),
    sa.Column('tipo_terceiro', sa.String(length=40), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('regime_iva', sa.String(length=60), nullable=True),
    sa.Column('isento_iva', sa.Boolean(), nullable=False),
    sa.Column('retencao_fonte', sa.Boolean(), nullable=False),
    sa.Column('reparticao_fiscal', sa.String(length=120), nullable=True),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.Column('iban', sa.String(length=60), nullable=True),
    sa.Column('swift', sa.String(length=20), nullable=True),
    sa.Column('condicoes_pagamento', sa.String(length=40), nullable=True),
    sa.Column('desconto_comercial', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('responsavel', sa.String(length=200), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_terceiros_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terceiros')),
    sa.UniqueConstraint('empresa_id', 'tipo', 'numero', name='terceiro_numero')
    )
    op.create_index(op.f('ix_terceiros_conta'), 'terceiros', ['conta'], unique=False)
    op.create_index(op.f('ix_terceiros_empresa_id'), 'terceiros', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_terceiros_nif'), 'terceiros', ['nif'], unique=False)
    op.create_index(op.f('ix_terceiros_nome'), 'terceiros', ['nome'], unique=False)
    op.create_index(op.f('ix_terceiros_tipo'), 'terceiros', ['tipo'], unique=False)
    op.create_table('vendedores',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_comissao', sa.String(length=20), nullable=False),
    sa.Column('comissao_perc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_vendedores_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendedores'))
    )
    op.create_index(op.f('ix_vendedores_empresa_id'), 'vendedores', ['empresa_id'], unique=False)
    op.create_table('compras',
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('documento_codigo', sa.String(length=10), nullable=False),
    sa.Column('documento_nome', sa.String(length=200), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('fornecedor_id', sa.Uuid(), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=200), nullable=True),
    sa.Column('armazem_id', sa.Uuid(), nullable=True),
    sa.Column('iva_perc', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('emitido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['armazem_id'], ['armazens.id'], name=op.f('fk_compras_armazem_id_armazens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_compras_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['terceiros.id'], name=op.f('fk_compras_fornecedor_id_terceiros'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compras')),
    sa.UniqueConstraint('empresa_id', 'numero', name='compra_numero')
    )
    op.create_index('ix_compras_empresa_data', 'compras', ['empresa_id', 'data'], unique=False)
    op.create_index(op.f('ix_compras_empresa_id'), 'compras', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_compras_estado'), 'compras', ['estado'], unique=False)
    op.create_index(op.f('ix_compras_fornecedor_id'), 'compras', ['fornecedor_id'], unique=False)
    op.create_table('diario_fechos',
    sa.Column('diario_codigo', sa.String(length=10), nullable=False),
    sa.Column('exercicio_id', sa.Uuid(), nullable=True),
    sa.Column('mes', sa.String(length=2), nullable=False),
    sa.Column('por', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_diario_fechos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name=op.f('fk_diario_fechos_exercicio_id_exercicios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diario_fechos')),
    sa.UniqueConstraint('empresa_id', 'diario_codigo', 'exercicio_id', 'mes', name='diario_fecho')
    )
    op.create_index(op.f('ix_diario_fechos_empresa_id'), 'diario_fechos', ['empresa_id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('numero_op', sa.String(length=30), nullable=True),
    sa.Column('doc_num', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('mes', sa.String(length=2), nullable=False),
    sa.Column('diario_codigo', sa.String(length=10), nullable=False),
    sa.Column('documento_codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('documento_ref', sa.String(length=60), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('exercicio_id', sa.Uuid(), nullable=True),
    sa.Column('diferido', sa.Boolean(), nullable=False),
    sa.Column('integrado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integrado_por', sa.String(length=200), nullable=True),
    sa.Column('criado_por', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_lancamentos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name=op.f('fk_lancamentos_exercicio_id_exercicios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos'))
    )
    op.create_index(op.f('ix_lancamentos_data'), 'lancamentos', ['data'], unique=False)
    op.create_index(op.f('ix_lancamentos_diario_codigo'), 'lancamentos', ['diario_codigo'], unique=False)
    op.create_index(op.f('ix_lancamentos_diferido'), 'lancamentos', ['diferido'], unique=False)
    op.create_index('ix_lancamentos_empresa_data', 'lancamentos', ['empresa_id', 'data'], unique=False)
    op.create_index('ix_lancamentos_empresa_exercicio', 'lancamentos', ['empresa_id', 'exercicio_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_empresa_id'), 'lancamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_exercicio_id'), 'lancamentos', ['exercicio_id'], unique=False)
    op.create_table('notas_texto',
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('exercicio_id', sa.Uuid(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_notas_texto_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name=op.f('fk_notas_texto_exercicio_id_exercicios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas_texto')),
    sa.UniqueConstraint('empresa_id', 'numero', 'exercicio_id', name='nota_texto')
    )
    op.create_index(op.f('ix_notas_texto_empresa_id'), 'notas_texto', ['empresa_id'], unique=False)
    op.create_table('processos_amortizacao',
    sa.Column('exercicio_id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.String(length=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('itens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_amort', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('por', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_processos_amortizacao_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name=op.f('fk_processos_amortizacao_exercicio_id_exercicios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processos_amortizacao')),
    sa.UniqueConstraint('empresa_id', 'exercicio_id', 'mes', name='processo_amortizacao')
    )
    op.create_index(op.f('ix_processos_amortizacao_empresa_id'), 'processos_amortizacao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_processos_amortizacao_exercicio_id'), 'processos_amortizacao', ['exercicio_id'], unique=False)
    op.create_table('rh_alteracoes',
    sa.Column('colaborador_id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('faltas', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('abonos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('descontos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name=op.f('fk_rh_alteracoes_colaborador_id_colaboradores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_alteracoes_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_alteracoes')),
    sa.UniqueConstraint('empresa_id', 'colaborador_id', 'mes', name='alteracao_mes')
    )
    op.create_index(op.f('ix_rh_alteracoes_colaborador_id'), 'rh_alteracoes', ['colaborador_id'], unique=False)
    op.create_index(op.f('ix_rh_alteracoes_empresa_id'), 'rh_alteracoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rh_alteracoes_mes'), 'rh_alteracoes', ['mes'], unique=False)
    op.create_table('rh_mapa_irt',
    sa.Column('colaborador_id', sa.Uuid(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('sub_alimentacao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_transporte', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('abono_familia', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reembolso_despesas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('outros_nao_sujeitos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('abono_falhas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_renda_casa', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('compensacao_rescisao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_ferias', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('horas_extras', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_atavio', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_representacao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('premios', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sub_natal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('outros_sujeitos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calc_manual_excesso', sa.Boolean(), nullable=False),
    sa.Column('excesso_subsidios_nao_sujeitos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('registo_manual_ss', sa.Boolean(), nullable=False),
    sa.Column('base_tributavel_ss_manual', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nao_sujeito_ss', sa.Boolean(), nullable=False),
    sa.Column('isento_irt', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name=op.f('fk_rh_mapa_irt_colaborador_id_colaboradores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_mapa_irt_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_mapa_irt')),
    sa.UniqueConstraint('empresa_id', 'colaborador_id', 'mes', name='mapa_irt_mes')
    )
    op.create_index(op.f('ix_rh_mapa_irt_colaborador_id'), 'rh_mapa_irt', ['colaborador_id'], unique=False)
    op.create_index(op.f('ix_rh_mapa_irt_empresa_id'), 'rh_mapa_irt', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rh_mapa_irt_mes'), 'rh_mapa_irt', ['mes'], unique=False)
    op.create_table('sequencias_documento',
    sa.Column('documento_codigo', sa.String(length=10), nullable=False),
    sa.Column('exercicio_id', sa.Uuid(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_sequencias_documento_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name=op.f('fk_sequencias_documento_exercicio_id_exercicios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequencias_documento')),
    sa.UniqueConstraint('empresa_id', 'documento_codigo', 'exercicio_id', name='sequencia_documento')
    )
    op.create_index(op.f('ix_sequencias_documento_empresa_id'), 'sequencias_documento', ['empresa_id'], unique=False)
    op.create_table('compra_linhas',
    sa.Column('compra_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Uuid(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('preco', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artigo_id'], ['artigos.id'], name=op.f('fk_compra_linhas_artigo_id_artigos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], name=op.f('fk_compra_linhas_compra_id_compras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra_linhas'))
    )
    op.create_index(op.f('ix_compra_linhas_compra_id'), 'compra_linhas', ['compra_id'], unique=False)
    op.create_table('lancamento_linhas',
    sa.Column('lancamento_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Uuid(), nullable=True),
    sa.Column('conta_codigo', sa.String(length=20), nullable=False),
    sa.Column('conta_nome', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entidade', sa.String(length=200), nullable=True),
    sa.Column('tipo_entidade', sa.String(length=20), nullable=True),
    sa.Column('iva_perc', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('perc_nao_ded', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('iva_autoliq', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('cambio', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('centro_codigo', sa.String(length=20), nullable=True),
    sa.Column('fluxo_codigo', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], name=op.f('fk_lancamento_linhas_conta_id_contas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_lancamento_linhas_lancamento_id_lancamentos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamento_linhas'))
    )
    op.create_index(op.f('ix_lancamento_linhas_centro_codigo'), 'lancamento_linhas', ['centro_codigo'], unique=False)
    op.create_index(op.f('ix_lancamento_linhas_fluxo_codigo'), 'lancamento_linhas', ['fluxo_codigo'], unique=False)
    op.create_index(op.f('ix_lancamento_linhas_lancamento_id'), 'lancamento_linhas', ['lancamento_id'], unique=False)
    op.create_index('ix_linhas_conta', 'lancamento_linhas', ['conta_codigo'], unique=False)
    op.create_table('movimentos_stock',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('artigo_id', sa.Uuid(), nullable=False),
    sa.Column('artigo_desc', sa.String(length=300), nullable=True),
    sa.Column('armazem_id', sa.Uuid(), nullable=False),
    sa.Column('armazem_destino_id', sa.Uuid(), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('custo_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('documento', sa.String(length=60), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('entidade', sa.String(length=200), nullable=True),
    sa.Column('lancamento_id', sa.Uuid(), nullable=True),
    sa.Column('numero_op', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['armazem_destino_id'], ['armazens.id'], name=op.f('fk_movimentos_stock_armazem_destino_id_armazens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['armazem_id'], ['armazens.id'], name=op.f('fk_movimentos_stock_armazem_id_armazens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artigo_id'], ['artigos.id'], name=op.f('fk_movimentos_stock_artigo_id_artigos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_movimentos_stock_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_movimentos_stock_lancamento_id_lancamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentos_stock')),
    sa.UniqueConstraint('empresa_id', 'numero', name='movimento_numero')
    )
    op.create_index(op.f('ix_movimentos_stock_armazem_id'), 'movimentos_stock', ['armazem_id'], unique=False)
    op.create_index(op.f('ix_movimentos_stock_artigo_id'), 'movimentos_stock', ['artigo_id'], unique=False)
    op.create_index(op.f('ix_movimentos_stock_empresa_id'), 'movimentos_stock', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimentos_stock_tipo'), 'movimentos_stock', ['tipo'], unique=False)
    op.create_index('ix_movs_artigo_data', 'movimentos_stock', ['artigo_id', 'data'], unique=False)
    op.create_index('ix_movs_empresa_data', 'movimentos_stock', ['empresa_id', 'data'], unique=False)
    op.create_table('rh_honorarios',
    sa.Column('independente_id', sa.Uuid(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('bruto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxa', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('retencao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('liquido', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('lancamento_id', sa.Uuid(), nullable=True),
    sa.Column('numero_op', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_honorarios_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['independente_id'], ['rh_independentes.id'], name=op.f('fk_rh_honorarios_independente_id_rh_independentes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_rh_honorarios_lancamento_id_lancamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_honorarios'))
    )
    op.create_index(op.f('ix_rh_honorarios_empresa_id'), 'rh_honorarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rh_honorarios_independente_id'), 'rh_honorarios', ['independente_id'], unique=False)
    op.create_table('rh_pagamentos',
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('lancamento_id', sa.Uuid(), nullable=True),
    sa.Column('numero_op', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_pagamentos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_rh_pagamentos_lancamento_id_lancamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_pagamentos')),
    sa.UniqueConstraint('empresa_id', 'mes', name='pagamento_mes')
    )
    op.create_index(op.f('ix_rh_pagamentos_empresa_id'), 'rh_pagamentos', ['empresa_id'], unique=False)
    op.create_table('rh_processamentos',
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('totais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('lancamento_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rh_processamentos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_rh_processamentos_lancamento_id_lancamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rh_processamentos')),
    sa.UniqueConstraint('empresa_id', 'mes', name='processamento_mes')
    )
    op.create_index(op.f('ix_rh_processamentos_empresa_id'), 'rh_processamentos', ['empresa_id'], unique=False)
    op.create_table('vendas',
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('tipo_doc', sa.String(length=4), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=200), nullable=True),
    sa.Column('vendedor_id', sa.Uuid(), nullable=True),
    sa.Column('iva_perc', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('emitido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('codigo_validacao', sa.String(length=20), nullable=True),
    sa.Column('conta_recebimento', sa.String(length=20), nullable=True),
    sa.Column('doc_origem_num', sa.String(length=30), nullable=True),
    sa.Column('lancamento_id', sa.Uuid(), nullable=True),
    sa.Column('numero_op', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['terceiros.id'], name=op.f('fk_vendas_cliente_id_terceiros'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_vendas_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], name=op.f('fk_vendas_lancamento_id_lancamentos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], name=op.f('fk_vendas_vendedor_id_vendedores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendas')),
    sa.UniqueConstraint('empresa_id', 'numero', name='venda_numero')
    )
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index('ix_vendas_empresa_data', 'vendas', ['empresa_id', 'data'], unique=False)
    op.create_index(op.f('ix_vendas_empresa_id'), 'vendas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vendas_estado'), 'vendas', ['estado'], unique=False)
    op.create_table('venda_linhas',
    sa.Column('venda_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('artigo_id', sa.Uuid(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('preco', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artigo_id'], ['artigos.id'], name=op.f('fk_venda_linhas_artigo_id_artigos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_venda_linhas_venda_id_vendas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venda_linhas'))
    )
    op.create_index(op.f('ix_venda_linhas_venda_id'), 'venda_linhas', ['venda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venda_linhas_venda_id'), table_name='venda_linhas')
    op.drop_table('venda_linhas')
    op.drop_index(op.f('ix_vendas_estado'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_empresa_id'), table_name='vendas')
    op.drop_index('ix_vendas_empresa_data', table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_rh_processamentos_empresa_id'), table_name='rh_processamentos')
    op.drop_table('rh_processamentos')
    op.drop_index(op.f('ix_rh_pagamentos_empresa_id'), table_name='rh_pagamentos')
    op.drop_table('rh_pagamentos')
    op.drop_index(op.f('ix_rh_honorarios_independente_id'), table_name='rh_honorarios')
    op.drop_index(op.f('ix_rh_honorarios_empresa_id'), table_name='rh_honorarios')
    op.drop_table('rh_honorarios')
    op.drop_index('ix_movs_empresa_data', table_name='movimentos_stock')
    op.drop_index('ix_movs_artigo_data', table_name='movimentos_stock')
    op.drop_index(op.f('ix_movimentos_stock_tipo'), table_name='movimentos_stock')
    op.drop_index(op.f('ix_movimentos_stock_empresa_id'), table_name='movimentos_stock')
    op.drop_index(op.f('ix_movimentos_stock_artigo_id'), table_name='movimentos_stock')
    op.drop_index(op.f('ix_movimentos_stock_armazem_id'), table_name='movimentos_stock')
    op.drop_table('movimentos_stock')
    op.drop_index('ix_linhas_conta', table_name='lancamento_linhas')
    op.drop_index(op.f('ix_lancamento_linhas_lancamento_id'), table_name='lancamento_linhas')
    op.drop_index(op.f('ix_lancamento_linhas_fluxo_codigo'), table_name='lancamento_linhas')
    op.drop_index(op.f('ix_lancamento_linhas_centro_codigo'), table_name='lancamento_linhas')
    op.drop_table('lancamento_linhas')
    op.drop_index(op.f('ix_compra_linhas_compra_id'), table_name='compra_linhas')
    op.drop_table('compra_linhas')
    op.drop_index(op.f('ix_sequencias_documento_empresa_id'), table_name='sequencias_documento')
    op.drop_table('sequencias_documento')
    op.drop_index(op.f('ix_rh_mapa_irt_mes'), table_name='rh_mapa_irt')
    op.drop_index(op.f('ix_rh_mapa_irt_empresa_id'), table_name='rh_mapa_irt')
    op.drop_index(op.f('ix_rh_mapa_irt_colaborador_id'), table_name='rh_mapa_irt')
    op.drop_table('rh_mapa_irt')
    op.drop_index(op.f('ix_rh_alteracoes_mes'), table_name='rh_alteracoes')
    op.drop_index(op.f('ix_rh_alteracoes_empresa_id'), table_name='rh_alteracoes')
    op.drop_index(op.f('ix_rh_alteracoes_colaborador_id'), table_name='rh_alteracoes')
    op.drop_table('rh_alteracoes')
    op.drop_index(op.f('ix_processos_amortizacao_exercicio_id'), table_name='processos_amortizacao')
    op.drop_index(op.f('ix_processos_amortizacao_empresa_id'), table_name='processos_amortizacao')
    op.drop_table('processos_amortizacao')
    op.drop_index(op.f('ix_notas_texto_empresa_id'), table_name='notas_texto')
    op.drop_table('notas_texto')
    op.drop_index(op.f('ix_lancamentos_exercicio_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_empresa_id'), table_name='lancamentos')
    op.drop_index('ix_lancamentos_empresa_exercicio', table_name='lancamentos')
    op.drop_index('ix_lancamentos_empresa_data', table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_diferido'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_diario_codigo'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_data'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_diario_fechos_empresa_id'), table_name='diario_fechos')
    op.drop_table('diario_fechos')
    op.drop_index(op.f('ix_compras_fornecedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_estado'), table_name='compras')
    op.drop_index(op.f('ix_compras_empresa_id'), table_name='compras')
    op.drop_index('ix_compras_empresa_data', table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_vendedores_empresa_id'), table_name='vendedores')
    op.drop_table('vendedores')
    op.drop_index(op.f('ix_terceiros_tipo'), table_name='terceiros')
    op.drop_index(op.f('ix_terceiros_nome'), table_name='terceiros')
    op.drop_index(op.f('ix_terceiros_nif'), table_name='terceiros')
    op.drop_index(op.f('ix_terceiros_empresa_id'), table_name='terceiros')
    op.drop_index(op.f('ix_terceiros_conta'), table_name='terceiros')
    op.drop_table('terceiros')
    op.drop_index(op.f('ix_sequencias_venda_empresa_id'), table_name='sequencias_venda')
    op.drop_table('sequencias_venda')
    op.drop_index(op.f('ix_rh_independentes_nome'), table_name='rh_independentes')
    op.drop_index(op.f('ix_rh_independentes_empresa_id'), table_name='rh_independentes')
    op.drop_table('rh_independentes')
    op.drop_index(op.f('ix_fluxos_empresa_id'), table_name='fluxos')
    op.drop_table('fluxos')
    op.drop_index(op.f('ix_documentos_contabilisticos_empresa_id'), table_name='documentos_contabilisticos')
    op.drop_table('documentos_contabilisticos')
    op.drop_index(op.f('ix_diarios_empresa_id'), table_name='diarios')
    op.drop_table('diarios')
    op.drop_index(op.f('ix_contas_empresa_id'), table_name='contas')
    op.drop_index('ix_contas_empresa_codigo', table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_colaboradores_nome'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_empresa_id'), table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_index(op.f('ix_centros_custo_empresa_id'), table_name='centros_custo')
    op.drop_table('centros_custo')
    op.drop_index(op.f('ix_ativos_empresa_id'), table_name='ativos')
    op.drop_table('ativos')
    op.drop_index(op.f('ix_artigos_empresa_id'), table_name='artigos')
    op.drop_index(op.f('ix_artigos_descricao'), table_name='artigos')
    op.drop_table('artigos')
    op.drop_index(op.f('ix_armazens_empresa_id'), table_name='armazens')
    op.drop_table('armazens')
    # ### end Alembic commands ###
